modLoader="javafml" #mandatory

loaderVersion="[44,)" #mandatory

license="Creative Commons Zero v1.0 Universal"

[[mods]] #mandatory

modId="asimplerubymod" #mandatory

version="1.0.0" #mandatory

displayName="A Simple Ruby Mod" #mandatory

authors="Pickle_Face5" #optional

description='''
A simple ruby mod!

Adds rubies and all ruby related equipment.

Compatible with most mods!
'''

versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
